### ISSUE TITLE
`IllegalArgumentException` at `DEL` command option handling

### ISSUE THREAD

**Issue by mj610-kim** [mj610-kim/excellent-code#39]
Codebase: https://github.com/mj610-kim/excellent-code/commit/4cef02e8360e1e40c07353505cbd61dd4989e288

Input file: 
```
ADD, , , ,15123099,VXIHXOTH JHOP,CL3,010-3112-2609,19771211,ADV
ADD, , , ,17112609,FB NTAWR,CL4,010-5645-6122,19861203,PRO
ADD, , , ,18115040,TTETHU HBO,CL3,010-4581-2050,20080718,ADV
ADD, , , ,88114052,NQ LVARW,CL4,010-4528-3059,19911021,PRO
ADD, , , ,19129568,SRERLALH HMEF,CL2,010-3091-9521,19640910,PRO
ADD, , , ,17111236,VSID TVO,CL1,010-3669-1077,20120718,PRO
ADD, , , ,18117906,TWU QSOLT,CL4,010-6672-7186,20030413,PRO
ADD, , , ,08123556,WN XV,CL1,010-7986-5047,20100614,PRO
ADD, , , ,02117175,SBILHUT LDEXRI,CL4,010-2814-1699,19950704,ADV
ADD, , , ,03113260,HH LTUPF,CL2,010-5798-5383,19791018,PRO
ADD, , , ,14130827,RPO JK,CL4,010-3231-1698,20090201,ADV
ADD, , , ,01122329,DN WD,CL4,010-7174-5680,20071117,PRO
ADD, , , ,08108827,RTAH VNUP,CL4,010-9031-2726,19780417,ADV
ADD, , , ,85125741,FBAH RTIJ,CL1,010-8900-1478,19780228,ADV
ADD, , , ,08117441,BMU MPOSXU,CL3,010-2703-3153,20010215,ADV
ADD, , , ,10127115,KBU MHU,CL3,010-3284-4054,19660814,ADV
ADD, , , ,12117017,LFIS JJIVL,CL1,010-7914-4067,20120812,PRO
ADD, , , ,11125777,TKOQKIS HC,CL1,010-6734-2289,19991001,PRO
ADD, , , ,11109136,QKAHCEX LTODDO,CL4,010-2627-8566,19640130,PRO
ADD, , , ,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,-p,-d, ,birthday,04
MOD,-p, , ,name,FB NTAWR,birthday,20050520
SCH, , , ,employeeNum,79110836
DEL, , , ,employeeNum,18115040
DEL,-p,-l, ,name,MPOSXU
SCH,-p, , ,certi,PRO
SCH, , , ,certi,ADV
SCH,-p, , ,cl,CL4
SCH, ,-m, ,birthday,09
MOD,-p, , ,name,FB NTAWR,cl,CL3
MOD,-p, , ,employeeNum,08123556,birthday,20110706
SCH,-p,-y, ,birthday,2003
SCH,-p, , ,employeeNum,05101762
SCH,-p,-m, ,phoneNum,3112
SCH,-p,-l, ,phoneNum,4605
SCH,-p, , ,employeeNum,10127115
MOD,-p, , ,phoneNum,010-8900-1478,certi,PRO
SCH, ,-f, ,name,LDEXRI
MOD, , , ,name,VCUHLE HMU,birthday,19910808
SCH, , , ,name,FB NTAWR
```

Crash logs:
```
[...]
input: DEL, , , ,employeeNum,18115040
cmd: DEL
employee: [employeeNum, 18115040]
colName: employeeNum, colVal: 18115040, optionsList: [ ,  ]
Exception in thread "main" java.lang.IllegalArgumentException: Invalid column(employeeNum)
	at com.cra08.excellentcode.optionhandler.Option2.processOption(Option2.java:45)
	at com.cra08.excellentcode.optionhandler.OptionHandler.processOptions(OptionHandler.java:19)
	at com.cra08.excellentcode.CommandHandler.handleDelCmd(CommandHandler.java:88)
	at com.cra08.excellentcode.CommandHandler.handleInput(CommandHandler.java:55)
	at com.cra08.excellentcode.CommandHandler.run(CommandHandler.java:38)
	at com.cra08.excellentcode.Main.main(Main.java:11)
```

**Comment by mj610-kim** [comment]
@taemin00 , please take a look!

**Comment by taemin00** [comment]
내용 공유 감사합니다! 해당 문제는 Option2.processOption()에서 empty string("")을 처리하지 못했기 때문인 것으로 보입니다.
수정하여 다시 PR올렸습니다!

**Comment by mj610-kim** [comment]
PR #40 을 체리픽하고 돌려봤는데, 아직 문제가 있는 것 같습니다. 혹시 `""` 말고 `" "` 등 도 핸들링이 필요할까요?

git log:
```
$ git log --oneline
5198532 (HEAD -> feature/implement-commandhandler) bug fix: handle null option in Option2.processOption()
4cef02e (origin/feature/implement-commandhandler) add code to return final result. use the result String to store to localFileWriter
31333c3 Add implementation of handleDelCmd
d1158dd clean up run()
dfef429 Create database member variable at CommnadHandler init and add to DB upon add cmd
```

Crash logs:
```
[...]
input: DEL, , , ,employeeNum,18115040
cmd: DEL
employee: [employeeNum, 18115040]
colName: employeeNum, colVal: 18115040, optionsList: [ ,  ]
Exception in thread "main" java.lang.IllegalArgumentException: Invalid column(employeeNum)
	at com.cra08.excellentcode.optionhandler.Option2.processOption(Option2.java:45)
	at com.cra08.excellentcode.optionhandler.OptionHandler.processOptions(OptionHandler.java:19)
	at com.cra08.excellentcode.CommandHandler.handleDelCmd(CommandHandler.java:88)
	at com.cra08.excellentcode.CommandHandler.handleInput(CommandHandler.java:55)
	at com.cra08.excellentcode.CommandHandler.run(CommandHandler.java:38)
	at com.cra08.excellentcode.Main.main(Main.java:11)
```

**Comment by mj610-kim** [comment]
@seongjin-Park210 님, @taemin00 님과 구두로 논의해본 결과, 공백 처리는 `CommandParser`에서 하는 것이 더 좋아보입니다. 이슈 assign해드립니다!

**Comment by mj610-kim** [comment]
#40 에서 부분적 fix가 반영됐습니다. `CommandParser` fix가 반영되면 close하겠습니다.

**Comment by mj610-kim** [comment]
Resolved by #43
