### ISSUE TITLE
Wrong output

### ISSUE THREAD

**Issue by mj610-kim** [mj610-kim/excellent-code#46]
Codebase:
`feature/implement-commandhandler` latest as of 2022-03-21 22:13
```
07136ab (HEAD -> feature/implement-commandhandler, origin/feature/implement-commandhandler) close files when exception is met
b7408d2 [DO NOT MERGE] WIP implementation of CommandHandler
629c858 (origin/develop, develop) Merge pull request #43 from mj610-kim/feature/implement-CommandParser-exception
[...]
```

We have a wrong output for a given input.

input.txt:
```
ADD, , , ,15123099,VXIHXOTH JHOP,CL3,010-3112-2609,19771211,ADV
ADD, , , ,17112609,FB NTAWR,CL4,010-5645-6122,19861203,PRO
ADD, , , ,18115040,TTETHU HBO,CL3,010-4581-2050,20080718,ADV
ADD, , , ,88114052,NQ LVARW,CL4,010-4528-3059,19911021,PRO
ADD, , , ,19129568,SRERLALH HMEF,CL2,010-3091-9521,19640910,PRO
ADD, , , ,17111236,VSID TVO,CL1,010-3669-1077,20120718,PRO
ADD, , , ,18117906,TWU QSOLT,CL4,010-6672-7186,20030413,PRO
ADD, , , ,08123556,WN XV,CL1,010-7986-5047,20100614,PRO
ADD, , , ,02117175,SBILHUT LDEXRI,CL4,010-2814-1699,19950704,ADV
ADD, , , ,03113260,HH LTUPF,CL2,010-5798-5383,19791018,PRO
ADD, , , ,14130827,RPO JK,CL4,010-3231-1698,20090201,ADV
ADD, , , ,01122329,DN WD,CL4,010-7174-5680,20071117,PRO
ADD, , , ,08108827,RTAH VNUP,CL4,010-9031-2726,19780417,ADV
ADD, , , ,85125741,FBAH RTIJ,CL1,010-8900-1478,19780228,ADV
ADD, , , ,08117441,BMU MPOSXU,CL3,010-2703-3153,20010215,ADV
ADD, , , ,10127115,KBU MHU,CL3,010-3284-4054,19660814,ADV
ADD, , , ,12117017,LFIS JJIVL,CL1,010-7914-4067,20120812,PRO
ADD, , , ,11125777,TKOQKIS HC,CL1,010-6734-2289,19991001,PRO
ADD, , , ,11109136,QKAHCEX LTODDO,CL4,010-2627-8566,19640130,PRO
ADD, , , ,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,-p,-d, ,birthday,04
MOD,-p, , ,name,FB NTAWR,birthday,20050520
SCH, , , ,employeeNum,79110836
DEL, , , ,employeeNum,18115040
DEL,-p,-l, ,name,MPOSXU
SCH,-p, , ,certi,PRO
SCH, , , ,certi,ADV
SCH,-p, , ,cl,CL4
SCH, ,-m, ,birthday,09
MOD,-p, , ,name,FB NTAWR,cl,CL3
MOD,-p, , ,employeeNum,08123556,birthday,20110706
SCH,-p,-y, ,birthday,2003
SCH,-p, , ,employeeNum,05101762
SCH,-p,-m, ,phoneNum,3112
SCH,-p,-l, ,phoneNum,4605
SCH,-p, , ,employeeNum,10127115
MOD,-p, , ,phoneNum,010-8900-1478,certi,PRO
SCH, ,-f, ,name,LDEXRI
MOD, , , ,name,VCUHLE HMU,birthday,19910808
SCH, , , ,name,FB NTAWR
```

output_expected:
```
SCH,02117175,SBILHUT LDEXRI,CL4,010-2814-1699,19950704,ADV
MOD,17112609,FB NTAWR,CL4,010-5645-6122,19861203,PRO
SCH,NONE
DEL,1
DEL,08117441,BMU MPOSXU,CL3,010-2703-3153,20010215,ADV
SCH,88114052,NQ LVARW,CL4,010-4528-3059,19911021,PRO
SCH,01122329,DN WD,CL4,010-7174-5680,20071117,PRO
SCH,03113260,HH LTUPF,CL2,010-5798-5383,19791018,PRO
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,08123556,WN XV,CL1,010-7986-5047,20100614,PRO
SCH,6
SCH,88114052,NQ LVARW,CL4,010-4528-3059,19911021,PRO
SCH,01122329,DN WD,CL4,010-7174-5680,20071117,PRO
SCH,02117175,SBILHUT LDEXRI,CL4,010-2814-1699,19950704,ADV
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,08108827,RTAH VNUP,CL4,010-9031-2726,19780417,ADV
SCH,1
MOD,17112609,FB NTAWR,CL4,010-5645-6122,20050520,PRO
MOD,08123556,WN XV,CL1,010-7986-5047,20100614,PRO
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,18117906,TWU QSOLT,CL4,010-6672-7186,20030413,PRO
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,15123099,VXIHXOTH JHOP,CL3,010-3112-2609,19771211,ADV
SCH,NONE
SCH,10127115,KBU MHU,CL3,010-3284-4054,19660814,ADV
MOD,85125741,FBAH RTIJ,CL1,010-8900-1478,19780228,ADV
SCH,NONE
MOD,1
SCH,1
```

output_actual:
```
SCH,02117175,SBILHUT LDEXRI,CL4,010-2814-1699,19950704,ADV
MOD,17112609,FB NTAWR,CL4,010-5645-6122,19861203,PRO
SCH,NONE
DEL,1
DEL,NONE
SCH,03113260,HH LTUPF,CL2,010-5798-5383,19791018,PRO
SCH,11125777,TKOQKIS HC,CL1,010-6734-2289,19991001,PRO
SCH,17112609,FB NTAWR,CL4,010-5645-6122,20050520,PRO
SCH,08123556,WN XV,CL1,010-7986-5047,20100614,PRO
SCH,18117906,TWU QSOLT,CL4,010-6672-7186,20030413,PRO
SCH,7
SCH,02117175,SBILHUT LDEXRI,CL4,010-2814-1699,19950704,ADV
SCH,17112609,FB NTAWR,CL4,010-5645-6122,20050520,PRO
SCH,18117906,TWU QSOLT,CL4,010-6672-7186,20030413,PRO
SCH,14130827,RPO JK,CL4,010-3231-1698,20090201,ADV
SCH,01122329,DN WD,CL4,010-7174-5680,20071117,PRO
SCH,NONE
```

**Comment by mj610-kim** [comment]
#47로 일부 fix 되었습니다! @taemin00 님 감사합니다!

현재 `develop` 브랜치 기준으로 expected와 actual의 diff입니다.

output_expected:
```
SCH,02117175,SBILHUT LDEXRI,CL4,010-2814-1699,19950704,ADV
MOD,17112609,FB NTAWR,CL4,010-5645-6122,19861203,PRO
SCH,NONE
DEL,1
DEL,08117441,BMU MPOSXU,CL3,010-2703-3153,20010215,ADV
SCH,88114052,NQ LVARW,CL4,010-4528-3059,19911021,PRO
SCH,01122329,DN WD,CL4,010-7174-5680,20071117,PRO
SCH,03113260,HH LTUPF,CL2,010-5798-5383,19791018,PRO
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,08123556,WN XV,CL1,010-7986-5047,20100614,PRO
SCH,6
SCH,88114052,NQ LVARW,CL4,010-4528-3059,19911021,PRO
SCH,01122329,DN WD,CL4,010-7174-5680,20071117,PRO
SCH,02117175,SBILHUT LDEXRI,CL4,010-2814-1699,19950704,ADV
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,08108827,RTAH VNUP,CL4,010-9031-2726,19780417,ADV
SCH,1
MOD,17112609,FB NTAWR,CL4,010-5645-6122,20050520,PRO
MOD,08123556,WN XV,CL1,010-7986-5047,20100614,PRO
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,18117906,TWU QSOLT,CL4,010-6672-7186,20030413,PRO
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,15123099,VXIHXOTH JHOP,CL3,010-3112-2609,19771211,ADV
SCH,NONE
SCH,10127115,KBU MHU,CL3,010-3284-4054,19660814,ADV
MOD,85125741,FBAH RTIJ,CL1,010-8900-1478,19780228,ADV
SCH,NONE
MOD,1
SCH,1
```

output_actual.txt:
```
SCH,02117175,SBILHUT LDEXRI,CL4,010-2814-1699,19950704,ADV
MOD,17112609,FB NTAWR,CL4,010-5645-6122,19861203,PRO
SCH,NONE
DEL,1
DEL,08117441,BMU MPOSXU,CL3,010-2703-3153,20010215,ADV
SCH,88114052,NQ LVARW,CL4,010-4528-3059,19911021,PRO
SCH,01122329,DN WD,CL4,010-7174-5680,20071117,PRO
SCH,03113260,HH LTUPF,CL2,010-5798-5383,19791018,PRO
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,08123556,WN XV,CL1,010-7986-5047,20100614,PRO
SCH,6
SCH,88114052,NQ LVARW,CL4,010-4528-3059,19911021,PRO
SCH,01122329,DN WD,CL4,010-7174-5680,20071117,PRO
SCH,02117175,SBILHUT LDEXRI,CL4,010-2814-1699,19950704,ADV
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,08108827,RTAH VNUP,CL4,010-9031-2726,19780417,ADV
SCH,NONE
```

**Comment by mj610-kim** [comment]
#47로 일부 fix 되었습니다! @taemin00 님 감사합니다!

현재 `develop` 브랜치 기준으로 expected와 actual의 diff입니다.

output_expected:
```
SCH,02117175,SBILHUT LDEXRI,CL4,010-2814-1699,19950704,ADV
MOD,17112609,FB NTAWR,CL4,010-5645-6122,19861203,PRO
SCH,NONE
DEL,1
DEL,08117441,BMU MPOSXU,CL3,010-2703-3153,20010215,ADV
SCH,88114052,NQ LVARW,CL4,010-4528-3059,19911021,PRO
SCH,01122329,DN WD,CL4,010-7174-5680,20071117,PRO
SCH,03113260,HH LTUPF,CL2,010-5798-5383,19791018,PRO
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,08123556,WN XV,CL1,010-7986-5047,20100614,PRO
SCH,6
SCH,88114052,NQ LVARW,CL4,010-4528-3059,19911021,PRO
SCH,01122329,DN WD,CL4,010-7174-5680,20071117,PRO
SCH,02117175,SBILHUT LDEXRI,CL4,010-2814-1699,19950704,ADV
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,08108827,RTAH VNUP,CL4,010-9031-2726,19780417,ADV
SCH,1
MOD,17112609,FB NTAWR,CL4,010-5645-6122,20050520,PRO
MOD,08123556,WN XV,CL1,010-7986-5047,20100614,PRO
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,18117906,TWU QSOLT,CL4,010-6672-7186,20030413,PRO
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,15123099,VXIHXOTH JHOP,CL3,010-3112-2609,19771211,ADV
SCH,NONE
SCH,10127115,KBU MHU,CL3,010-3284-4054,19660814,ADV
MOD,85125741,FBAH RTIJ,CL1,010-8900-1478,19780228,ADV
SCH,NONE
MOD,1
SCH,1
```

output_actual.txt:
```
SCH,02117175,SBILHUT LDEXRI,CL4,010-2814-1699,19950704,ADV
MOD,17112609,FB NTAWR,CL4,010-5645-6122,19861203,PRO
SCH,NONE
DEL,1
DEL,08117441,BMU MPOSXU,CL3,010-2703-3153,20010215,ADV
SCH,88114052,NQ LVARW,CL4,010-4528-3059,19911021,PRO
SCH,01122329,DN WD,CL4,010-7174-5680,20071117,PRO
SCH,03113260,HH LTUPF,CL2,010-5798-5383,19791018,PRO
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,08123556,WN XV,CL1,010-7986-5047,20100614,PRO
SCH,6
SCH,88114052,NQ LVARW,CL4,010-4528-3059,19911021,PRO
SCH,01122329,DN WD,CL4,010-7174-5680,20071117,PRO
SCH,02117175,SBILHUT LDEXRI,CL4,010-2814-1699,19950704,ADV
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,08108827,RTAH VNUP,CL4,010-9031-2726,19780417,ADV
SCH,NONE
```

**Comment by mj610-kim** [comment]
`run()` 중간에 exception으로 인해 프로그램이 조기 종료 되는 것으로 보입니다:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 4
	at java.lang.String.substring(String.java:1963)
	at com.cra08.excellentcode.Employee.<init>(Employee.java:32)
	at com.cra08.excellentcode.column.ColumnCl.setValue(ColumnCl.java:8)
	at com.cra08.excellentcode.storage.Database.mod(Database.java:48)
	at com.cra08.excellentcode.CommandHandler.handleModCmd(CommandHandler.java:150)
	at com.cra08.excellentcode.CommandHandler.handleInput(CommandHandler.java:77)
	at com.cra08.excellentcode.CommandHandler.run(CommandHandler.java:46)
	at com.cra08.excellentcode.Main.main(Main.java:11)
```

**Comment by mj610-kim** [comment]
#53 으로 해당 TC 관련 버그는 모두 수정된 것으로 보입니다.\

output_actual:
```
SCH,02117175,SBILHUT LDEXRI,CL4,010-2814-1699,19950704,ADV
MOD,17112609,FB NTAWR,CL4,010-5645-6122,19861203,PRO
SCH,NONE
DEL,1
DEL,08117441,BMU MPOSXU,CL3,010-2703-3153,20010215,ADV
SCH,88114052,NQ LVARW,CL4,010-4528-3059,19911021,PRO
SCH,01122329,DN WD,CL4,010-7174-5680,20071117,PRO
SCH,03113260,HH LTUPF,CL2,010-5798-5383,19791018,PRO
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,08123556,WN XV,CL1,010-7986-5047,20100614,PRO
SCH,6
SCH,88114052,NQ LVARW,CL4,010-4528-3059,19911021,PRO
SCH,01122329,DN WD,CL4,010-7174-5680,20071117,PRO
SCH,02117175,SBILHUT LDEXRI,CL4,010-2814-1699,19950704,ADV
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,08108827,RTAH VNUP,CL4,010-9031-2726,19780417,ADV
SCH,1
MOD,17112609,FB NTAWR,CL4,010-5645-6122,20050520,PRO
MOD,08123556,WN XV,CL1,010-7986-5047,20100614,PRO
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,18117906,TWU QSOLT,CL4,010-6672-7186,20030413,PRO
SCH,05101762,VCUHLE HMU,CL4,010-3988-9289,20030819,PRO
SCH,15123099,VXIHXOTH JHOP,CL3,010-3112-2609,19771211,ADV
SCH,NONE
SCH,10127115,KBU MHU,CL3,010-3284-4054,19660814,ADV
MOD,85125741,FBAH RTIJ,CL1,010-8900-1478,19780228,ADV
SCH,NONE
MOD,1
SCH,1
```
